### ISSUE TITLE
[Mod Suggestion] Just Enough Resources

### ISSUE THREAD

**Issue by rafaeltab** [NillerMedDild/Enigmatica8#11]
### URL

https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/3552801

### Why would you like the mod added?

It makes it way easier to find the source of an item, right now if you want to find how to get a feather you can't even find that. This mod would change that.

It's still in Alpha right now, but should update to at least to beta soon, hopefully.

**Comment by NillerMedDild** [comment]
I'll consider it :)

**Comment by NillerMedDild** [comment]
Added and disabled worldgen, as it's wildly inaccurate. The min Y is still 0 for example :P 

I'm worried it will increase world join times as the pack grows, and because of that I may end up removing it after a while.
