### ISSUE TITLE
[Mod Suggestion] Open Blocks Elevators

### ISSUE THREAD

**Issue by rafaeltab** [NillerMedDild/Enigmatica8#12]
### URL

https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator/files

### Why would you like the mod added?

No more walking up the stairs from y -64 to y 319.

It's in beta right now, maybe a full release in the future?

**Comment by NillerMedDild** [comment]
It's already in the pack.

**Comment by rafaeltab** [comment]
I am so sorry, I thought I checked but apparently I did not

**Comment by NillerMedDild** [comment]
No worries :)
