### ISSUE TITLE
[Mod Suggestion] Croptopia

### ISSUE THREAD

**Issue by Mang0z** [NillerMedDild/Enigmatica8#15]
### URL

https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric

### Why would you like the mod added?

Its a pretty good alternative to Simple farming and simple farming doesnt seem to be on 1.18 currently
(I know the link says "fabric" but its for both forge and fabric)

**Comment by NillerMedDild** [comment]
I think just having Farmer's Delight is good for now :)
