### ISSUE TITLE
Terralith 2.0

### ISSUE THREAD

**Issue by MrBrebby** [NillerMedDild/Enigmatica8#21]
### URL

https://www.curseforge.com/minecraft/mc-mods/terralith

### Why would you like the mod added?

Honestly, I just created this account to suggest Terralith, and support Create.

I think having both of those mods would substantially improve an already incredible modpack.

**Comment by TGMax233Michael** [comment]
To be clear: It is **not compatible** with most of the mods modifying the world generation. (Official note)
So if there's any plan to add something like BOP or OTBYG and so on, it might not be a good idea. 
:3

**Comment by MrBrebby** [comment]
> To be clear: It is **not compatible** with most of the mods modifying the world generation. (Official note) So if there's any plan to add something like BOP or OTBYG and so on, it might not be a good idea. :3

Fair play.

**Comment by theboo** [comment]
> To be clear: It is **not compatible** with most of the mods modifying the world generation. (Official note) So if there's any plan to add something like BOP or OTBYG and so on, it might not be a good idea. :3

To be even more clear: right now, no biome mods are compatible with each other...

**Comment by NillerMedDild** [comment]
I'm getting very heavy lag while exploring :/ gonna mark this as blocked for the time being and try again later.

**Comment by MrBrebby** [comment]
Makes sense; even with my testing and a very minor accompaniment of mods, I experienced quite a bit of lag as well.

Thank you for trying.  Merry Christmas/Happy New Year.

Hopefully this can be optimized by the main author later on.  (Also, hurray for Create.)
