### ISSUE TITLE
UtilitiX

### ISSUE THREAD

**Issue by MelanX** [NillerMedDild/Enigmatica8#24]
### URL

https://www.curseforge.com/minecraft/mc-mods/utilitix

### Why would you like the mod added?

It's a cool mod which adds a few useful items and blocks. I would compare it with Cyclic as it adds several stuff, too. There will still stuff be added.
Things worth to be mentioned:
- Advanced Brewery -> combine/clone/upgrade potions
- Wireless redstone repeater -> connect a few to a little "network"
- Experience Crystal -> stores XP, collects XP orbs, has a gui to store/retrieve XP
- Glue -> connect blocks together and use a piston to move all at once
- and a few more...

**Comment by NillerMedDild** [comment]
I'd rather not add a random stuff mod to be honest, that's one of the reasons Cyclic isn't added anymore.
