### ISSUE TITLE
Bumblezone for 1.18.1

### ISSUE THREAD

**Issue by TelepathicGrunt** [NillerMedDild/Enigmatica8#28]
### URL

https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

### Why would you like the mod added?

I heard of bumblezone being suggested for 1.16.5 back when it was newish and it was declined for being too lacking. Now it is 1.18.1 and the mod was filled out quite a bit and has quite a bit of customizability. Including Beehemoth, Honey Fluid, and Pollen Puffs. I thought it wouldn't hurt for me to post a suggestion here to revisit the mod and see what you think lol. (technically, one can add new biomes to The Bumblezone by making a datapack and have the new biome json be under the the_bumblezone namespace and the mod pulls it in automatically. But that's more trickier to work with)

Let me know if there's anything problematic about it. As other Bee themed mods port to 1.18.1, I'll add compat with them back. Right now it has Productive Bees compat and Pokecube compat. Resourceful bees compat is planned for when they get ported.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion.

Do you have an idea of what Resourceful Bee compat will consist of? :)

The Bumblezone seems better now than when I first checked it out, but it's still a little bland to be honest. There's nothing that really encourages me to stay in the dimension, other than initial exploration.

**Comment by TelepathicGrunt** [comment]
When resourceful bees is ported, Bumblezone will be able to spawn their bees and honeycombs within the dimension to act as an alternative places to ore mine or find new bees by chance. This will be controlled by a tag whitelist so I’ll try and keep out any overpowered bees or combs.

i am open to other suggestions or ideas for compat and the dimension lol.

**Comment by NillerMedDild** [comment]
That is tempting then, a dedicated dimension for hunting Resourceful Bees would be nice.
