### ISSUE TITLE
[Mod Suggestion] Dust

### ISSUE THREAD

**Issue by Mowmaster** [NillerMedDild/Enigmatica8#3]
### URL

https://www.curseforge.com/minecraft/mc-mods/dust/files/3548552

### Why would you like the mod added?

Is a rewrite of an old 1.12 magic mod, that adds its own unique 'flavor' of magic not seen before in other main stream magic mods.
The 1.18 version is going to include the Pedestals mod from 1.16 in it, but be way more balanced, as well as a few other mods from the same author.
There will eventually be an almost 'Thaumcraft' style research system in it, along with various mobs that can be friended and used for automation, Dunegons, Structures, and other sorts of exploration that should fit in nicely with the 1.18 caves and cliffs update.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion. I've checked it out in-world and I'm not really feeling it to be honest, I may revisit it later on in the development cycle though.
