### ISSUE TITLE
[Mod Suggestion] Salem

### ISSUE THREAD

**Issue by Buuz135** [NillerMedDild/Enigmatica8#4]
### URL

https://www.curseforge.com/minecraft/mc-mods/salem

### Why would you like the mod added?

Rid made textures for it

**Comment by NillerMedDild** [comment]
I don't know Buuz... :P

**Comment by NillerMedDild** [comment]
I've played around with the commands and liked how it worked tbh, needs playtesting though :D

**Comment by Ridanisaurus** [comment]
It's fine. It's a mod by Buuz. What could possibly go wrong. :D
