### ISSUE TITLE
Server doesn't start due to betterf3 accessing client side classes

### ISSUE THREAD

**Issue by rafaeltab** [NillerMedDild/Enigmatica8#8]
### Modpack Version

Clone at `merge pull request #7` commit `673b3b7`

### Describe your issue.

After precisely following the setup for automation for servers, an error occurs (can be found in the latest log section).

Exact steps to reproduce:
* git clone
* Open the automation folder.
* Run the script InstanceSyncSetup.bat
* Run the script update-server.ps1
* go back to root
* run the script start-automated-server.bat
* set  the eula to true when prompted
* press any key in the server command prompt

Temporary fix: remove betterf3 from mods folder

### Latest Log

https://gist.github.com/rafaeltab/fd596d103eb9ce79e96b114c70be8f6f

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by RaVenInTheDark** [comment]
BetterF3 looks to be client side only, so ensuring servers don't download it would be an adequate fix.

**Comment by NillerMedDild** [comment]
D'oh! I fixed it for the server files but not for auto servers 😅 sorry about that!

**Comment by rafaeltab** [comment]
Good job! on getting this resolved this quick
