### ISSUE TITLE
'Gobber'

### ISSUE THREAD

**Issue by Thiana** [NillerMedDild/Enigmatica8#9]
### URL

https://www.curseforge.com/minecraft/mc-mods/gobber

### Why would you like the mod added?

It adds some QOL trinkets/tools/etc which we normally get from Botania/etc. Some of them are a bit OP (the repair ring for example) but those could be disabled or gated for end game.

Thanks.

**Comment by NillerMedDild** [comment]
I'd rather wait for other mods for these kinds of tools, getting all of this stuff through a few new ores seems boring/unoriginal to me.
